scionproto-contrib/jpan

README.md
pom.xml
src/main/java/org/scion/DaemonClient.java
src/main/java/org/scion/ScionException.java
src/main/java/org/scion/Util.java
src/test/java/org/scion/DaemonTest.java
src/test/java/org/scion/testutil/MockDaemon.java

Daemon connection

---

.github/workflows/build.yml
CHANGELOG.md
TODO.md
src/main/java/org/scion/DatagramChannel.java
src/main/java/org/scion/ScionService.java
src/main/java/org/scion/Scmp.java
src/main/java/org/scion/ScmpChannel.java
src/main/java/org/scion/internal/ScionHeaderParser.java
src/main/java/org/scion/internal/ScmpParser.java
src/test/java/org/scion/PackageVisibilityHelper.java
src/test/java/org/scion/ScionBootstrapperTest.java
src/test/java/org/scion/api/DatagramChannelApiTest.java
src/test/java/org/scion/api/SCMPTest.java
src/test/java/org/scion/demo/PingPongChannelClient.java
src/test/java/org/scion/demo/PingPongChannelServer.java
src/test/java/org/scion/demo/ScmpEchoDemo.java
src/test/java/org/scion/demo/ScmpTracerouteDemo.java
src/test/java/org/scion/demo/inspector/ScionHeader.java
src/test/java/org/scion/demo/inspector/ScionPacketInspector.java
src/test/java/org/scion/demo/inspector/ScmpHeader.java
src/test/java/org/scion/demo/inspector/ScmpInspectorTest.java
src/test/java/org/scion/internal/HeaderParseAndReplyTest.java
src/test/java/org/scion/testutil/MockNetwork.java
src/test/java/org/scion/testutil/PingPongHelper.java

Clean up more unit tests.
- Implement SCMP tests
- Fix any issues 
- Implement SCMP timeout and error handling (IO errors and SCMP errors)

SCMP unit test cleanup

---

CHANGELOG.md
TODO.md
src/main/java/org/scion/AbstractDatagramChannel.java
src/main/java/org/scion/DatagramChannel.java
src/test/java/org/scion/api/DatagramChannelApiTest.java
src/test/java/org/scion/testutil/DNSUtil.java
src/test/java/org/scion/testutil/MockNetwork.java

Cleanup and small fixes for 0.1.0
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/netsec-ethz/scion-java-client/32)

Cleanup for 0.1.0

---

CHANGELOG.md
src/test/java/org/scion/testutil/JUnitSetUp.java
src/test/java/org/scion/testutil/MockDaemon.java
src/test/resources/META-INF/services/org.junit.jupiter.api.extension.Extension
src/test/resources/junit-platform.properties

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/netsec-ethz/scion-java-client/38)

Global JUnit settings

---

CHANGELOG.md
src/main/java/org/scion/jpan/internal/MultiMap.java
src/main/java/org/scion/jpan/internal/Segments.java
src/test/java/org/scion/jpan/internal/MultiMapTest.java

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/netsec-ethz/scion-java-client/45)

Fix JPAN refactoring

---

CHANGELOG.md
README.md
src/main/java/org/scion/jpan/internal/HostsFileParser.java
src/main/java/org/scion/jpan/internal/ScionBootstrapper.java
src/test/java/org/scion/jpan/api/ScionTest.java

Improve bootstrap logging

---

CHANGELOG.md
src/main/java/org/scion/jpan/internal/ScionBootstrapper.java
src/test/java/org/scion/jpan/api/ScionTest.java
src/test/resources/topologies/topology-scionproto-0.11.json

Support new public field in topo file

---

CHANGELOG.md
README.md
doc/DevEnvironment.md

Add some documentation with hints for setting up a development environment.

Doc hints for dev environment

---

CHANGELOG.md
src/main/java/org/scion/jpan/PathPolicy.java
src/main/java/org/scion/jpan/RequestPath.java
src/main/java/org/scion/jpan/ScionDatagramChannel.java
src/main/java/org/scion/jpan/ScionDatagramSocket.java
src/main/java/org/scion/jpan/ScionUtil.java
src/test/java/org/scion/jpan/api/DatagramChannelApiTest.java
src/test/java/org/scion/jpan/api/DatagramSocketApiTest.java
src/test/java/org/scion/jpan/api/ScionServiceTest.java
src/test/java/org/scion/jpan/demo/ScmpEchoDemo.java
src/test/java/org/scion/jpan/demo/ScmpTracerouteDemo.java
src/test/java/org/scion/jpan/demo/ShowpathsDemo.java

Move path metadata to separate class.

PathMetadata

---

CHANGELOG.md
src/main/java/org/scion/jpan/PathMetadata.java
src/main/java/org/scion/jpan/ScionService.java
src/main/java/org/scion/jpan/ScionUtil.java
src/main/java/org/scion/jpan/ScmpChannel.java
src/main/java/org/scion/jpan/internal/ScionBootstrapper.java
src/test/java/org/scion/jpan/api/SCMPTest.java
src/test/java/org/scion/jpan/demo/ScmpEchoDemo.java
src/test/java/org/scion/jpan/demo/ScmpTracerouteDemo.java
src/test/java/org/scion/jpan/testutil/MockDaemon.java

SCMP echo problems, see #96.
This PR does not resolve the issue but clears up some other problems

SCMP echo problems, see #96

---

CHANGELOG.md
src/main/java/org/scion/jpan/PathMetadata.java
src/main/java/org/scion/jpan/ScionService.java
src/main/java/org/scion/jpan/ScmpChannel.java
src/test/java/org/scion/jpan/api/SCMPTest.java
src/test/java/org/scion/jpan/demo/ScmpEchoDemo.java
src/test/java/org/scion/jpan/demo/ScmpTracerouteDemo.java
src/test/java/org/scion/jpan/demo/ShowpathsDemo.java
src/test/java/org/scion/jpan/demo/test/PingPongChannelDemoTest.java
src/test/java/org/scion/jpan/demo/test/ScmpEchoDemoTest.java
src/test/java/org/scion/jpan/demo/test/ScmpTracerouteDemoTest.java
src/test/java/org/scion/jpan/demo/test/ShowpathDemoTest.java
src/test/java/org/scion/jpan/demo/test/ShowpathsDemoTest.java
src/test/java/org/scion/jpan/testutil/MockNetwork.java
src/test/java/org/scion/jpan/testutil/MockScmpHandler.java

This is not a valid destination address, see https://www.iana.org/assignments/iana-ipv4-special-registry/iana-ipv4-special-registry.xhtml

Remove use of 0.0.0.0

---

CHANGELOG.md
src/test/java/org/scion/jpan/api/DatagramSocketConcurrentPingPongTest.java

Concurrency test takes too long

---

CHANGELOG.md
README.md

0.3.0 preparation

---

CHANGELOG.md
pom.xml

LICENSE in jar

---

CHANGELOG.md
src/test/java/org/scion/jpan/ProtobufPathDemo.java
src/test/java/org/scion/jpan/api/DatagramChannelPacketValidationTest.java
src/test/java/org/scion/jpan/api/ScionTest.java
src/test/java/org/scion/jpan/api/ScmpSenderTest.java
src/test/java/org/scion/jpan/demo/ScmpDemoDefault.java
src/test/java/org/scion/jpan/demo/ScmpEchoDemo.java
src/test/java/org/scion/jpan/demo/inspector/ScionHeader.java
src/test/java/org/scion/jpan/demo/test/PingPongChannelDemoTest.java
src/test/java/org/scion/jpan/demo/test/PingPongSocketDemoTest.java
src/test/java/org/scion/jpan/internal/NatMappingTest.java
src/test/java/org/scion/jpan/testutil/TestUtil.java

New TestUtil class to consolidate utility functions.

TestUtil class

---

CHANGELOG.md
doc/NAT.md
src/main/java/org/scion/jpan/AbstractDatagramChannel.java
src/main/java/org/scion/jpan/internal/STUN.java
src/test/java/org/scion/jpan/internal/StunTest.java

Clients need to be able to respond to STUN requests.

NAT client responder

---

CHANGELOG.md
README.md

Fix slf4j example

---

README.md

Update README.md logging example

---

CHANGELOG.md
README.md
doc/ReleaseHowTo.md

Recompiled with JDK 8 `javac`.

Release 0.5.1

---

.github/workflows/build.yml
CHANGELOG.md
src/main/java/org/scion/jpan/ScionService.java
src/test/java/org/scion/jpan/api/ScionServiceTest.java
src/test/java/org/scion/jpan/internal/HeaderComposeTest.java
src/test/java/org/scion/jpan/internal/InspectorComposeTest.java
src/test/java/org/scion/jpan/internal/NatMappingTest.java
src/test/java/org/scion/jpan/testutil/PingPongHelperBase.java

`ScionService.close()` should not throw `IOException`

ScionService.close() should not throw IOException

---

CHANGELOG.md
pom.xml
src/main/java/org/scion/jpan/AbstractDatagramChannel.java
src/test/java/org/scion/jpan/internal/ShimTest.java

Avoid server intra-AS response sent to shim dispatcher

---

CHANGELOG.md
README.md

Add instructions for getting a path from an IP
