CHANGELOG.md, TODO.md, config/checkstyle/java.header.txt, pom.xml
Changed maven `artifactId` from `scion-java-client` to `client`.
=> artifactID + year + TODO

CHANGELOG.md, TODO.md, src/main/java/org/scion/ScionService.java, src/test/java/org/scion/demo/DemoConstants.java, src/test/java/org/scion/demo/DemoTopology.java, src/test/java/org/scion/demo/PingPongChannelClient.java, src/test/java/org/scion/demo/PingPongChannelServer.java, src/test/java/org/scion/demo/PingPongDemoTest.java, src/test/java/org/scion/testutil/MockTopologyServer.java
CI builds fail with 
```
[INFO] -------------------------------------------------------
[INFO]  T E S T S
[INFO] -------------------------------------------------------
[INFO] Running org.scion.api.DatagramChannelMultiSendPathTest
[INFO] Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.829 s -- in org.scion.api.DatagramChannelMultiSendPathTest
[INFO] Running org.scion.api.DatagramChannelApiTest
[INFO] Tests run: 28, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.694 s -- in org.scion.api.DatagramChannelApiTest
[INFO] Running org.scion.api.ScionUtilTest
[INFO] Tests run: 6, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.011 s -- in org.scion.api.ScionUtilTest
[INFO] Running org.scion.api.ScionServiceTest
[INFO] Tests run: 11, Failures: 0, Errors: 0, Skipped: 0, …
```
=> CI build failure

CHANGELOG.md, README.md, TODO.md, doc/Design.md, src/main/java/org/scion/AbstractDatagramChannel.java, src/main/java/org/scion/DatagramChannel.java, src/main/java/org/scion/Scmp.java, src/main/java/org/scion/ScmpChannel.java, src/main/java/org/scion/ScmpDatagramChannel.java, src/main/java/org/scion/internal/ScionBootstrapper.java, src/main/java/org/scion/internal/ScmpParser.java, src/test/java/org/scion/PackageVisibilityHelper.java, src/test/java/org/scion/api/DatagramChannelApiTest.java, src/test/java/org/scion/api/SCMPTest.java, src/test/java/org/scion/demo/ScmpEchoDemo.java, src/test/java/org/scion/demo/ScmpTracerouteDemo.java, src/test/java/org/scion/demo/inspector/HopField.java, src/test/java/org/scion/demo/inspector/ScionPacketInspector.java, src/test/java/org/scion/demo/inspector/ScmpHeader.java, src/test/java/org/scion/testutil/MockNetwork.java
SCMP refactoring and cleanup
- Rename `Scmp.ScmpXYZ` to `Scmp.XYZ`
- Remove `Result<>`
- Move Scmp code out of DatagramChannel into separate class. Consider creating `AbstractScionChannel`.
=> SCMP refactoring and clean up

CHANGELOG.md, TODO.md, src/main/java/org/scion/RequestPath.java, src/main/java/org/scion/ScmpChannel.java, src/main/java/org/scion/internal/PathHeaderParser.java, src/main/java/org/scion/internal/ScionHeaderParser.java, src/test/java/org/scion/api/SCMPTest.java, src/test/java/org/scion/api/ScionServiceTest.java, src/test/java/org/scion/demo/ScmpEchoDemo.java, src/test/java/org/scion/demo/inspector/PathHeaderScion.java, src/test/java/org/scion/demo/inspector/ScionHeader.java, src/test/java/org/scion/demo/inspector/ScionPacketInspector.java, src/test/java/org/scion/testutil/MockDaemon.java, src/test/java/org/scion/testutil/MockNetwork.java
SCMP INFO requests fail in local AS (path length = 0).
=> Fix ping/trace in local AS

CHANGELOG.md, doc/Design.md, src/main/java/org/scion/AbstractDatagramChannel.java, src/main/java/org/scion/DatagramChannel.java, src/main/java/org/scion/ScionService.java, src/test/java/org/scion/PackageVisibilityHelper.java, src/test/java/org/scion/api/DatagramChannelApiServerTest.java, src/test/java/org/scion/api/DatagramChannelApiTest.java, src/test/java/org/scion/api/DatagramChannelErrorHandlingTest.java, src/test/java/org/scion/api/DatagramChannelPacketValidationTest.java, src/test/java/org/scion/api/ScionTest.java, src/test/java/org/scion/testutil/MockDatagramChannel.java
ScionService logic.
Avoid creation of services unless required. Verify that no service is created for server applications.
=> ScionService logic

CHANGELOG.md, src/main/java/org/scion/AbstractDatagramChannel.java, src/main/java/org/scion/RequestPath.java, src/test/java/org/scion/api/DatagramChannelApiTest.java
The DatagramChannel is mixing up connections of the underlying channel (to first hop) and the implemented channel (to a remote host).
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/netsec-ethz/scion-java-client/33)
=> Fix DatagramChannel connection tracking

CHANGELOG.md, src/main/java/org/scion/internal/MultiMap.java, src/main/java/org/scion/internal/Segments.java, src/test/java/org/scion/internal/MultiMapTest.java
Test and clean up `MultiMap`
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/netsec-ethz/scion-java-client/34)
=> MultiMap clean up

CHANGELOG.md, doc/Design.md, src/main/java/org/scion/AbstractDatagramChannel.java, src/main/java/org/scion/DatagramChannel.java, src/main/java/org/scion/ScionService.java, src/main/java/org/scion/ScionSocketOptions.java, src/main/java/org/scion/ScmpChannel.java, src/test/java/org/scion/api/DatagramChannelApiConcurrencyTest.java, src/test/java/org/scion/api/DatagramChannelApiTest.java, src/test/java/org/scion/api/DatagramChannelMultiSendInetAddrTest.java, src/test/java/org/scion/api/DatagramChannelMultiSendPathTest.java, src/test/java/org/scion/demo/PingPongChannelClient.java, src/test/java/org/scion/demo/PingPongDemoTest.java, src/test/java/org/scion/demo/inspector/ScionHeader.java, src/test/java/org/scion/demo/inspector/ScionPacketInspector.java, src/test/java/org/scion/testutil/MockDaemon.java, src/test/java/org/scion/testutil/MockDatagramChannel.java, src/test/java/org/scion/testutil/PingPongHelper.java, src/test/java/org/scion/testutil/PingPongHelperBase.java, src/test/java/org/scion/testutil/Util.java
`DatagramChannel` improvements:
- Better concurrency support
- Fixed handling of `connect()`, `disconnect()` and `bind()`
- Fixed buffer resizing with MTU
- Removed duplicate code
- General clean up
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/netsec-ethz/scion-java-client/35)
=> Channel clean up

CHANGELOG.md, src/main/java/org/scion/AbstractDatagramChannel.java, src/main/java/org/scion/internal/ScionHeaderParser.java, src/test/java/org/scion/api/DatagramChannelApiTest.java, src/test/java/org/scion/internal/HeaderComposeTest.java
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/netsec-ethz/scion-java-client/36)
=> Fix traffic class configuration

CHANGELOG.md, README.md, src/main/java/org/scion/Constants.java, src/main/java/org/scion/ScionService.java, src/test/java/org/scion/api/ScionTest.java, src/test/java/org/scion/demo/DemoTopology.java, src/test/java/org/scion/demo/ScmpTracerouteDemo.java, src/test/java/org/scion/testutil/MockDaemon.java
Merged SCION_DAEMON_HOST and SCION_DAEMON_PORT into a single SCION_DAEMON property.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/netsec-ethz/scion-java-client/39)
=> Merged SCION_DAEMON property

CHANGELOG.md, README.md, pom.xml, src/main/java/org/scion/Constants.java, src/main/java/org/scion/ScionService.java, src/main/java/org/scion/ScionSocketOptions.java, src/main/java/org/scion/internal/DNSHelper.java, src/main/java/org/scion/internal/HostsFileParser.java, src/main/java/org/scion/internal/ScionBootstrapper.java, src/main/java/org/scion/internal/Segments.java, src/test/java/org/scion/api/DatagramChannelApiTest.java, src/test/java/org/scion/api/ScionServiceTest.java, src/test/java/org/scion/demo/ScmpEchoDemo.java, src/test/java/org/scion/demo/ScmpTracerouteDemo.java, src/test/java/org/scion/testutil/DNSUtil.java, src/test/java/org/scion/testutil/JUnitSetUp.java, src/test/java/org/scion/testutil/MockTopologyServer.java, src/test/resources/etc-scion-hosts, src/test/resources/simplelogger.properties
Add support for /etc/scion/hosts and /etc/resolv.conf
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/netsec-ethz/scion-java-client/40)
=> /etc/scion/hosts and /etc/resolv.conf

CHANGELOG.md, pom.xml, src/main/java/org/scion/AbstractDatagramChannel.java, src/main/java/org/scion/ScionAddress.java, src/main/java/org/scion/ScionService.java, src/main/java/org/scion/internal/DNSHelper.java, src/main/java/org/scion/internal/HostsFileParser.java, src/test/java/org/scion/demo/PingPongDemoTest.java
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/netsec-ethz/scion-java-client/42)
=> Hosts file parser cleanup

CHANGELOG.md, src/main/java/org/scion/jpan/AbstractDatagramChannel.java, src/main/java/org/scion/jpan/Path.java, src/main/java/org/scion/jpan/RequestPath.java, src/main/java/org/scion/jpan/ResponsePath.java, src/main/java/org/scion/jpan/ScionService.java, src/main/java/org/scion/jpan/internal/ScionHeaderParser.java, src/test/java/org/scion/jpan/PackageVisibilityHelper.java, src/test/java/org/scion/jpan/api/DatagramChannelApiTest.java, src/test/java/org/scion/jpan/api/DatagramChannelMultiSendInetAddrTest.java, src/test/java/org/scion/jpan/api/DatagramChannelMultiSendPathTest.java, src/test/java/org/scion/jpan/api/DatagramChannelMultiWriteConnectedInetSocketTest.java, src/test/java/org/scion/jpan/api/SCMPTest.java, src/test/java/org/scion/jpan/api/ScionServiceTest.java, src/test/java/org/scion/jpan/api/ScionTest.java, src/test/java/org/scion/jpan/demo/ScmpEchoDemo.java, src/test/java/org/scion/jpan/testutil/PingPongHelper.java
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/netsec-ethz/scion-java-client/44)
=> Path should return InetAddress

CHANGELOG.md, README.md, src/main/java/org/scion/jpan/AbstractDatagramChannel.java, src/main/java/org/scion/jpan/DatagramChannel.java
Add support communicating with a dispatcher-endhost in the local AS, see `DatagramChannel.configureRemoteDispatcher`. 
This method ensures that local packets are sent to port 30041 on the remote host.
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/netsec-ethz/scion-java-client/46)
=> Support dispatcher in local AS

CHANGELOG.md, src/main/java/org/scion/jpan/internal/HostsFileParser.java, src/test/java/org/scion/jpan/api/ScionServiceTest.java, src/test/resources/etc-scion-hosts
Support for EOL comments, multiple spaces and tabs in `/etc/scion/hosts`
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/netsec-ethz/scion-java-client/47)
=> Improved /etc/scion/hosts parsing

CHANGELOG.md, src/main/java/org/scion/jpan/AbstractDatagramChannel.java, src/main/java/org/scion/jpan/ScionUtil.java, src/main/java/org/scion/jpan/ScmpChannel.java, src/main/java/org/scion/jpan/internal/ByteUtil.java, src/main/java/org/scion/jpan/internal/PathRawParser.java, src/test/java/org/scion/jpan/PackageVisibilityHelper.java, src/test/java/org/scion/jpan/api/ScionUtilTest.java, src/test/java/org/scion/jpan/demo/ScmpEchoDemo.java
Added methods to get the current path and local address from `ScmpChannel`.
Also added `toStringPath` methods to `ScionUtil`.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/netsec-ethz/scion-java-client/48)
=> Improved ScmpChannel

CHANGELOG.md, README.md, src/main/java/org/scion/jpan/Constants.java, src/main/java/org/scion/jpan/ScionUtil.java, src/test/java/org/scion/jpan/PackageVisibilityHelper.java, src/test/java/org/scion/jpan/testutil/JUnitSetUp.java
Add proper warnings if a daemon or control server is running locally.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/netsec-ethz/scion-java-client/50)
=> Improved test resilience

.github/workflows/build.yml, CHANGELOG.md, pom.xml
This happens on OSX M1 machines with Java > 8.
=> Fix "Unsupported platform: protoc-3.11.4-osx-aarch_64.exe"

CHANGELOG.md, src/main/java/org/scion/jpan/RequestPath.java, src/main/java/org/scion/jpan/ScionAddress.java, src/main/java/org/scion/jpan/ScionService.java, src/main/java/org/scion/jpan/internal/HostsFileParser.java, src/main/java/org/scion/jpan/internal/IPHelper.java, src/test/java/org/scion/jpan/api/ScionServiceTest.java, src/test/resources/etc-scion-hosts
Avoid DNS lookups caused by `InetAddress.getByName()`.
=> Avoid DNS lookup

CHANGELOG.md, src/main/java/org/scion/jpan/ScionService.java, src/main/java/org/scion/jpan/internal/HostsFileParser.java, src/test/java/org/scion/jpan/testutil/JUnitSetUp.java
Avoid `InetAddress.getHostName()` because it may trigger a reverse DNS lookup.
=> Avoid InetAddress.getHostName()

CHANGELOG.md, src/main/java/org/scion/jpan/ScionDatagramChannel.java, src/main/java/org/scion/jpan/ScionDatagramSocket.java, src/main/java/org/scion/jpan/ScionResponseAddress.java, src/main/java/org/scion/jpan/internal/SelectingDatagramChannel.java, src/test/java/org/scion/jpan/api/DatagramChannelApiConcurrencyTest.java, src/test/java/org/scion/jpan/api/DatagramChannelApiServerTest.java, src/test/java/org/scion/jpan/api/DatagramChannelMultiSendInetAddrTest.java, src/test/java/org/scion/jpan/api/DatagramChannelMultiSendPathTest.java, src/test/java/org/scion/jpan/api/DatagramChannelMultiWriteConnectedPathTest.java, src/test/java/org/scion/jpan/api/DatagramChannelStreamTest.java, src/test/java/org/scion/jpan/demo/PingPongChannelServer.java, src/test/java/org/scion/jpan/testutil/PingPongChannelHelper.java
`DatagramChannel.receive()` should return a subclass of `InetSocketAddress` that contains `ReturnPath` information. 
To do this we introduce a new `ScionReturnAddress` class that extends `InetSocketAddress`.
This allows paths to be returned by `DatagramChannel.receive()`. At the same time, a normal `Path` does not expose any `InetSocketAddress` methods to avoid confusion. In particular, as far as the user is concerned an InetSocketAddress is never a SCION address (it does not have ISD/AS), and a SCION resolved address is always a Path.
=> Path-aware subclasses InetSocketAddress

CHANGELOG.md, src/main/java/org/scion/jpan/AbstractDatagramChannel.java, src/main/java/org/scion/jpan/ScionDatagramChannel.java, src/main/java/org/scion/jpan/ScionDatagramSocket.java, src/main/java/org/scion/jpan/ScionService.java, src/main/java/org/scion/jpan/ScmpChannel.java, src/test/java/org/scion/jpan/testutil/PingPongHelperBase.java
Remove 'getPaths(InetSocketAddress)` because it wasn't clear that it performed a DNS lookup to resolve a SCION address.
Functionality has be changed to first to a lookup and then get the paths or call `lookupAndGetPaths`.
=> Remove ambiguous service.getPaths()

CHANGELOG.md, src/main/java/org/scion/jpan/AbstractDatagramChannel.java, src/main/java/org/scion/jpan/PathMetadata.java, src/main/java/org/scion/jpan/ScionDatagramChannel.java, src/test/java/org/scion/jpan/api/DatagramChannelApiTest.java
`DatagramChannel.send()` should return an `int` instead of a `Path`.
=> send() must return 'int'

CHANGELOG.md, src/main/java/org/scion/jpan/ScionAddress.java
Remove `getHostName()` from `ScionAddress`
=> remove getHostName()

CHANGELOG.md, README.md, pom.xml, src/main/java/org/scion/jpan/Constants.java, src/main/java/org/scion/jpan/ScionService.java, src/main/java/org/scion/jpan/internal/DNSHelper.java, src/main/java/org/scion/jpan/internal/PathRawParser.java, src/test/java/org/scion/jpan/api/ScionServiceTest.java, src/test/java/org/scion/jpan/testutil/JUnitSetUp.java
Add environment variable / property to specify DNS search domain
=> Configurable DNS search domain

CHANGELOG.md, TODO.md, pom.xml, src/main/java/org/scion/jpan/RequestPath.java, src/main/java/org/scion/jpan/ResponsePath.java, src/main/java/org/scion/jpan/ScionAddress.java, src/main/java/org/scion/jpan/ScionService.java, src/main/java/org/scion/jpan/Scmp.java, src/main/java/org/scion/jpan/ScmpChannel.java
- Remove deprecated code
- Update dependencies
=> Prepare 0.3.0

CHANGELOG.md, README.md, src/main/java/org/scion/jpan/internal/LocalTopology.java, src/test/java/org/scion/jpan/api/ScionTest.java, src/test/resources/topologies/no-discovery.json
Support topology files without discovery section
=> topofile without discovery

CHANGELOG.md, src/main/java/org/scion/jpan/internal/Segments.java, src/test/java/org/scion/jpan/internal/SegmentsMinimal211Test.java
The path construction algorithm failed to construct a path when it received an UP segment and an empty list of CORE segments.
The problem occurred because the algorithm was checking for `list==null` instead of `list==empty`.
=> Fix missing path in case of solitary core AS

CHANGELOG.md, src/main/java/org/scion/jpan/Scmp.java, src/main/java/org/scion/jpan/internal/ScionHeaderParser.java, src/main/java/org/scion/jpan/internal/Shim.java, src/test/java/org/scion/jpan/api/ScmpSenderTest.java, src/test/java/org/scion/jpan/demo/inspector/ScionHeader.java, src/test/java/org/scion/jpan/demo/inspector/ScionPacketInspector.java, src/test/java/org/scion/jpan/demo/inspector/ScmpHeader.java, src/test/java/org/scion/jpan/internal/HeaderParseAndReplyTest.java, src/test/java/org/scion/jpan/internal/ShimTest.java, src/test/java/org/scion/jpan/testutil/MockBorderRouter.java, src/test/java/org/scion/jpan/testutil/MockControlServer.java, src/test/java/org/scion/jpan/testutil/MockNetwork2.java
The dispatcher SHIM fails to forward SCMP errors and instead crashes.
Expected:
- The SHIM should never crash
- SCMP errors should be forwarded if possible, to the source port of the error-causing packet (unless the packet is truncated)
=> Fixed SHIM SCMP error forwarding

CHANGELOG.md, src/main/java/org/scion/jpan/internal/HostsFileParser.java
Add `/etc/hosts` to the default parsed host files (next to `/etc/scion/hosts`).
=> /etc/hosts

CHANGELOG.md, src/main/java/org/scion/jpan/AbstractDatagramChannel.java, src/main/java/org/scion/jpan/PathPolicy.java, src/main/java/org/scion/jpan/ScionDatagramChannel.java, src/main/java/org/scion/jpan/ScionDatagramSocket.java, src/main/java/org/scion/jpan/ppl/PplPolicy.java, src/test/java/org/scion/jpan/api/DatagramChannelApiTest.java, src/test/java/org/scion/jpan/api/PathPolicyLanguageGroupTest.java, src/test/java/org/scion/jpan/api/PathPolicyLanguageTest.java, src/test/java/org/scion/jpan/api/PathPolicyTest.java, src/test/java/org/scion/jpan/ppl/PathProvider.java, src/test/java/org/scion/jpan/ppl/PolicyTest.java
PathPolicies should accept or produce empty path lists without throwing an exception,
=> Don't throw exception on empty path list

CHANGELOG.md, pom.xml, src/main/java/org/scion/jpan/ScionService.java
Remove usage of `grpc-netty-shaded` because it causes problems with Android execution.
`grpc-netty` actually worked with android, but `grpc-okhttp` seems to be the better option because it promises compatibility with Android older version and check compatibility with current versions.
=> grpc-netty-shaded jar

CHANGELOG.md, src/test/java/org/scion/jpan/internal/NatMappingTest.java
Fix unstable NAT tests that often failed on MacOS.
=> NAT test stabilization

CHANGELOG.md, src/main/java/org/scion/jpan/internal/Segments.java
If no CORE segments are available, we should abort early instead of requesting DOWN segments.
=> Fixed error in case of no CORE
